=== Neumann-A/CMakeJSON/CMakeJSON/schemas/find.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://raw.githubusercontent.com/Neumann-A/CMakeJSON/main/CMakeJSON/schemas/find.schema.json",
    "title": "CMakeJSON Find Module Definition JSON",
    "description": "CMakeJSON Find Module Definition JSON. See https://github.com/Neumann-A/CMakeJSON/main/docs/find.md.",
    "type": "object",
    "$defs" : {
        "dependency" : {
            "oneOf": [ {
                "description" : "Name of the dependency for `find_package(name)`",
                "type": "string"
            },
            {
                "type" : "object",
                "properties" : {
                    "name" : {
                        "description" : "Name of the dependency for `find_package(name)`",
                        "type" : "string"
                    },
                    "version" : {
                        "description" : "Version of the dependency `find_package(<PackageName> <version>)`",
                        "type" : "string"
                    },
                    "components" :  {
                        "description" : "Components to add to `find_package(<PackageName> COMPONENTS <components>)`",
                        "type" : "string"
                    },
                    "find_options" : {
                        "description" : "Additional options to add to `find_package(<PackageName> <find_options>)`",
                        "type" : "string"
                    },
                    "condition" : {
                        "description" : "Condition to perform the `find_package()` call (Note: **Only** use this for platform based conditions. Option based conditions should list their dependencies under the relevant option!)",
                        "type" : "string"
                    }
                },
                "required" : [ "name" ]
            }
            ]
        }
    },
    "properties": {
        "description" : {
            "description" : "Description for the package. See [`feature_summary`](https://cmake.org/cmake/help/latest/module/FeatureSummary.html)",
            "type" : "string"
        },
        "config_name" : {
            "description" : "Alternative name to search for. Be aware `find_package` is case senstive!",
            "type" : "string",
            "default" : "`${CMake_FIND_PACKAGE_NAME}`"
        },
        "skip_config_mode" : {
            "description" : "Skip trying to use config mode.",
            "type" : "boolean",
            "default" : "OFF"
        },
        "pkg_config_name" : {
            "description" : "Alternative pkg-config name to search for.",
            "type" : "string",
            "default" : "lowercase `${CMake_FIND_PACKAGE_NAME}`"
        },
        "version_extraction" : {
            "description" : "Required information to extract/obtain a version if no (pkg/cmale)config is found",
            "type" : "object",
            "properties" :{
                "file" : {
                    "description" : "File to read in for version extraction",
                    "type" : "string"
                },
                "code" : {
                    "description" : "CMake code to obtain the version from file. Parameter 1 -> File Input. Paramter 2 -> Version Output",
                    "type" : "string"
                }
            }
        }
        ,
        "configurations" : {
            "description" : "Setup to search for different configurations.",
            "type" : "array",
            "items": {
                "type" : "object",
                "properties" :{
                    "config" : {
                        "description": "Name of the configuration",
                        "type" : "string"
                    },
                    "lib_prefixes" : {
                        "description": "additional library prefixes of the configuration",
                        "type" : "array",
                        "items": {
                            "type" : "string"
                        },
                        "uniqueItems": true
                    },
                    "lib_suffixes" : {
                        "description": "additional library suffixes of the configuration",
                        "type" : "array",
                        "items": {
                            "type" : "string"
                        },
                        "uniqueItems": true
                    }
                }
            },
            "uniqueItems": true,
            "default" : " [ \"{\"config\": \"DEBUG\", \"suffix\": [\"d\", \"_d\"]}\", \"{\"config\": \"RELEASE\"}\"]"
        },
        "dependencies" : {

        },
        "imported_targets" : {
            "type" : "array",
            "items" : {
                "type" : "object",
                "properties": {
                    "name" : {
                        "description": "Target name of the imported target",
                        "type" : "string"
                    },
                    "languages" : {
                        "description": "Link interface languages",
                        "type" : "array",
                        "items": {
                            "type" : "string"
                        },
                        "uniqueItems": true,
                        "default" : "[\"C\"]"
                    },
                    "library_names" : {
                        "description": "Name of the libraries to search for",
                        "type" : "array",
                        "items": {
                            "type" : "string"
                        },
                        "uniqueItems": true
                    },
                    "config_target" : {
                        "description": "Name of the target if found via an exported cmake config.",
                        "type" : "string"
                    },
                    "link_libraries" : {
                        "description": "Targets to link against! (Only interface)",
                        "type" : "array",
                        "items": {
                            "type" : "string"
                        }
                    },
                    "header_file" : {
                        "description": "Header file to search for to add to the include interface",
                        "type" : "array",
                        "items": {
                            "type" : "string"
                        }
                    },
                    "include_directories" : {
                        "description": "Include directories to add! (Only interface)",
                        "type" : "array",
                        "items": {
                            "type" : "string"
                        }
                    }
                }
            },
            "uniqueItems": true
        }
    }
}

=== Neumann-A/CMakeJSON/examples/SimpleProjectWithDep/cmake/FindDummy.json
{
    "skip_config_mode" : true,
    "dependencies" : [
        "Threads"
    ],
    "description" : "Just a dummy find module.",
    "imported_targets" : [{
        "name" : "${CMAKE_FIND_PACKAGE_NAME}",
        "library_names" : ["foo", "dummy"],
        "header_file" : [ "bar", "dummy.hpp"],
        "languages" : [ "CXX"]
    }]
}
